### ISSUE TITLE
Option creation not working

### ISSUE THREAD

**Issue by joelimgu** [OmenApps/django-tomselect#6]
I am trying to add ad "new" button, I followed the doc and created gave a Tom-select as the template for a widget with the add url:

```
widgets = {
            'city': TomSelectTabularWidget(
                    City,
                    url="tom-select-autocomplete",
                    add_url='city-create',
                )
        }
```

But nothing happens, the tom-select widget works but without any creation button to be seen.

Note: I am using bootstrap5 to render it IDK if it might affect it.

Do you have any examples in a project that you could share?

Thanks.

**Comment by jacklinke** [comment]
Resolved in 2024.12.2. Note this release has several breaking changes.
